### ISSUE TITLE
Great work! But I met some issues

### ISSUE THREAD

**Issue by a791702141** [KaiyangZhou/mixstyle-release#12]
Great works! It can get amazing results in image classification generalization. But when I run the reid code, I met this problem:

Traceback (most recent call last):
  File "main.py", line 214, in <module>
    main()
  File "main.py", line 139, in main
    cfg.merge_from_list(args.opts)
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['osnet_x1_0_ms23_a0d1', 'data.save_dir', 'output/osnet_x1_0_ms23_a0d1/market2duke']; it must be a list of pairs
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    main()
  File "main.py", line 139, in main
    cfg.merge_from_list(args.opts)
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['osnet_x1_0_ms23_a0d1', 'data.save_dir', 'output/osnet_x1_0_ms23_a0d1/duke2market']; it must be a list of pairs

And another problem is I don't find how to organize the data and where to download them, should I just put Market1501 and Duke in the same folder as "data_dir"?

**Comment by a791702141** [comment]
Thanks, I have solved the problem.

**Comment by Nirmala891** [comment]
> Thanks, I have solved the problem.

Hi, I am facing the same issue. Can you please help me out.
Thanks.
